[package]
name = "budgetman_crud"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
uuid = { version = "0.8", default-features = false, features = ["serde", "v4"] }
serde = "1"
anyhow = "1"
sea-query = "*"
sqlx = "*"
warp = "*"
